### ISSUE TITLE
Wrong Constant Name #<Seedbank

### ISSUE THREAD

**Issue by ltcdnunez** [james2m/seedbank#12]
I am unable to get the seeds working on Rails 3.2.6. I'm getting the error: `wrong constant name #<Seedbank` as soon as the execution begins for the first seed file. I've included the full backtrace below and am investigating on my end. I recognize that this could be specific to my system but I want to post this here in case anyone else is experiencing this problem.

``` bash
** Invoke db:structure:load_if_sql (first_time)
** Invoke db:create 
** Execute db:structure:load_if_sql
** Invoke db:seed (first_time)
** Invoke db:seed:common (first_time)
** Invoke db:seed:original (first_time)
** Execute db:seed:original
** Invoke db:abort_if_pending_migrations (first_time)
** Invoke environment 
** Execute db:abort_if_pending_migrations
** Invoke db:seed:countries (first_time)
** Invoke db:abort_if_pending_migrations 
** Execute db:seed:countries
rake aborted!
wrong constant name #<Seedbank
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/seedbank-0.2.0/lib/seedbank/dsl.rb:27:in `module_eval'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activesupport-3.2.0/lib/active_support/inflector/methods.rb:226:in `block in constantize'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activesupport-3.2.0/lib/active_support/inflector/methods.rb:225:in `each'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activesupport-3.2.0/lib/active_support/inflector/methods.rb:225:in `constantize'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activesupport-3.2.0/lib/active_support/core_ext/module/introspection.rb:31:in `parent'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activerecord-3.2.0/lib/active_record/model_schema.rb:325:in `compute_table_name'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activerecord-3.2.0/lib/active_record/model_schema.rb:151:in `reset_table_name'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activerecord-3.2.0/lib/active_record/model_schema.rb:104:in `table_name'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activerecord-3.2.0/lib/active_record/base.rb:427:in `arel_table'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activerecord-3.2.0/lib/active_record/base.rb:443:in `relation'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activerecord-3.2.0/lib/active_record/scoping/named.rb:37:in `scoped'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/activerecord-3.2.0/lib/active_record/querying.rb:7:in `delete_all'
(eval):7:in `block in define_seed_task'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/seedbank-0.2.0/lib/seedbank/dsl.rb:27:in `module_eval'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@harbinger/gems/seedbank-0.2.0/lib/seedbank/dsl.rb:27:in `block in define_seed_task'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:203:in `call'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:203:in `block in execute'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'
/home/dnunez/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/dnunez/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/dnunez/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:176:in `block in invoke_prerequisites'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `each'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:157:in `block in invoke_with_call_chain'
/home/dnunez/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/bin/rake:19:in `load'
/home/dnunez/.rvm/gems/ruby-1.9.3-p0@global/bin/rake:19:in `<main>'
```

**Comment by ashakumari** [comment]
I am still facing this issue with version 0.5.0 of the seedbank gem
